//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.PassportDatas = new HashSet<PassportData>();
        }
    
        public int Id { get; set; }
        public string City1 { get; set; }
    
        public virtual City Cities1 { get; set; }
        public virtual City City2 { get; set; }
        public virtual ICollection<PassportData> PassportDatas { get; set; }
    }
}
