//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportData
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string PassportNumber { get; set; }
        public int Sex { get; set; }
        public System.DateTime Birthday { get; set; }
        public int City { get; set; }
        public string Address { get; set; }
        public string IssuedBy { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string Code { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Sex Sex1 { get; set; }
    }
}
